### ISSUE TITLE
Ionic 4 Support

### ISSUE THREAD

**Issue by invot** [ZebraDevs/DataWedge-Ionic-Demo#13]
https://github.com/invot/ZebraIonicDemo - I created a fork that that supports Ionic 4 + Angular 8. Just finished testing it and, so far, it's working on my test device.  

Not sure if anyone is interested in this, but it helped me dramatically.

**Comment by cissemy** [comment]
Hi,
Any fix ?

**Comment by darryncampbell** [comment]
Finally got around to updating this project to Ionic 6 so the master branch should now work: https://github.com/ZebraDevs/DataWedge-Ionic-Demo/pull/16
