### ISSUE TITLE
enable side buttons

### ISSUE THREAD

**Issue by jjoao07** [ZebraDevs/DataWedge-Ionic-Demo#18]
Hi @darryncampbell 

Is there a way to trigger side buttons from this plugin or a guide to do so using this project.

I need to enable the side left and right buttons to scan programmatically, but not sure how I should invoke this functionality.

Regards

**Comment by jjoao07** [comment]
> Hi @darryncampbell
> 
> Is there a way to trigger side buttons from this plugin or a guide to do so using this project.
> 
> I need to enable the side left and right buttons to scan programmatically, but not sure how I should invoke this functionality.
> 
> Regards

I have fixed this.

**Comment by darryncampbell** [comment]
This **should** be the default behaviour but if not then please let me know.
