### ISSUE TITLE
uncaught exception in registerBroadcastReceiver

### ISSUE THREAD

**Issue by vinceweeks-69** [ZebraDevs/DataWedge-Ionic-Demo#19]
(<any>window).plugins.intentShim.registerBroadcastReceiver({ ... 

throws

 Uncaught (in promise): TypeError: Cannot read property 'intentShim' of undefined
TypeError: Cannot read property 'intentShim' of undefined

**Comment by vinceweeks-69** [comment]
actually the line is
(<any>window).plugins.intentShim.registerBroadcastReceiver({

**Comment by vinceweeks-69** [comment]
Sorry - my fault. I missed a step

**Comment by darryncampbell** [comment]
Hi Vince, yes you will need to install the https://www.npmjs.com/package/com-darryncampbell-cordova-plugin-intent plugin.  If you are using Capacitor then the instructions to do this are at https://capacitorjs.com/docs/cordova/using-cordova-plugins

**Comment by vinceweeks-69** [comment]
Wow - thanks for getting back to me Darryn. I have followed the Capacitor specific instructions and am no longer getting the exception. I'm still not getting any scan events though. Can I send you a snippet? 
    On Tuesday, January 26, 2021, 02:52:40 AM EST, Darryn <notifications@github.com> wrote:  
 
 


Hi Vince, yes you will need to install the https://www.npmjs.com/package/com-darryncampbell-cordova-plugin-intent plugin. If you are using Capacitor then the instructions to do this are at https://capacitorjs.com/docs/cordova/using-cordova-plugins

**Comment by darryncampbell** [comment]
Sure, maybe send through Dan

**Comment by vinceweeks-69** [comment]
As in Dan Silva? He asked that I go through GitHub. This is a quick one -
"plugin com.darryncampbell.cordova.plugin-intent requires to add <intent-filter>... to AndroidManifest.xml"
I get this message at build even though I've added the intent filter xml.On Tuesday, January 26, 2021, 06:53:51 AM EST, Darryn <notifications@github.com> wrote:
 
 
 


Sure, maybe send through Dan

**Comment by darryncampbell** [comment]
Sorry, I misunderstood... if you wanted to email files then please do so through Dan but if you are happy to paste in this chat then that may be easiest. 

> "plugin com.darryncampbell.cordova.plugin-intent requires to add <intent-filter>... to AndroidManifest.xml"
I get this message at build even though I've added the intent filter xml

You should not need to make any changes to the manifest, what error are you seeing?

**Comment by vinceweeks-69** [comment]
I talked to Dan this morning and we got it running. Thanks for you support, Darryn.
    On Tuesday, January 26, 2021, 08:22:55 AM EST, Darryn <notifications@github.com> wrote:  
 
 


Sorry, I misunderstood... if you wanted to email files then please do so through Dan but if you are happy to paste in this chat then that may be easiest.


"plugin com.darryncampbell.cordova.plugin-intent requires to add ... to AndroidManifest.xml"
I get this message at build even though I've added the intent filter xml


You should not need to make any changes to the manifest, what error are you seeing?
