### ISSUE TITLE
scanner recognition fail

### ISSUE THREAD

**Issue by youngkwon9509** [ZebraDevs/DataWedge-Ionic-Demo#20]
node-v14
ionic 6.13.1

If you receive the source and upload it to TC75, it will compile and install, 
but it will not be able to recognize barcodes.
(The scanner cannot be found.)
![zebra](https://user-images.githubusercontent.com/74492785/110405828-8ba93680-80c4-11eb-9a95-bf40b077f427.jpeg)

Are there any recommended node and ionic versions?

-----------------------------------------------------------------------------------------
03-09 10:48:03.316 3650-25153/? D/WearableController: Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=com.zebra.zebraionicdemo
03-09 10:48:03.329 25162-25162/? E/CameraBase: [Camera_Cont] Load controller interface
03-09 10:48:03.336 25162-25162/? E/ScannerFramework: [CreateTokenForDeathNotifier] Creating death notifier tokens
03-09 10:48:03.336 25162-25162/? E/CameraBase: [Camera_Cont] Load controller interface
03-09 10:48:03.336 25162-25162/? E/ScannerFramework: [CreateTokenForDeathNotifier] Creating death notifier tokens
03-09 10:48:03.359 25162-25162/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<

03-09 10:48:03.782 25162-25162/? E/ScannerFramework: [ReleaseDeathNotifierTokens] Releasing death notifier tokens
03-09 10:48:03.782 25162-25162/? E/ScannerFramework: [ReleaseDeathNotifierTokens] Releasing death notifier tokens

03-09 10:48:03.952 1916-1916/? E/NetworkScheduler.SchedulerReceiver: Invalid parameter app
03-09 10:48:03.952 1916-1916/? E/NetworkScheduler.SchedulerReceiver: Invalid package name : Perhaps you didn't include a PendingIntent in the extras?

**Comment by darryncampbell** [comment]
Did you configure your DataWedge profile manually?  If not, please see the ReadMe doc.  Once the DataWedge profile has been configured you should be able to scan and capture barcodes.  Note that the 'selected scanner' dropdown requires DataWedge 6.4 (I think) which will be why it does not get populated on your device.  The scanner defined in the DataWedge profile will be used, by default this is the 2D imager scanner.

**Comment by youngkwon9509** [comment]
I have manually set up the DataWedge profile.
The item of "Selected Scanner" only shows "Waiting".

![notscan](https://user-images.githubusercontent.com/74492785/110567307-9df2a580-8194-11eb-9bd3-d9102c546608.jpeg)
