### ISSUE TITLE
Relation between filter & app name

### ISSUE THREAD

**Issue by forexknight** [ZebraDevs/DataWedge-Ionic-Demo#21]
Hi,

I don't quite get the connection between widget id and it's name in `barcode.ts` file. 

In my application in config.xml if I have widget with id `com.zebra.zebraionicdemo` and in filters in `barcode.ts` file `com.zebra.ionicdemo.ACTION` everything works. The problem is that when I change my app id in `config.xml` to `com.exampleapp` and then put it into filters so it looks like `com.exampleapp.ACTION` it doesn't work.

Is this filter somehow hardcoded in the plugin itself? 
Could you explain how to associate the widget id with the filters in `barcode.ts` file?

**Comment by darryncampbell** [comment]
> Is this filter somehow hardcoded in the plugin itself?

It is not the filter that is hard coded but if you look at the associated apps for the profile (https://raw.githubusercontent.com/Zebra/ZebraIonicDemo/master/screenshots/profile_activities.png) you will need to modify this to point to your new app ID.  You can do this by changing https://github.com/ZebraDevs/DataWedge-Ionic-Demo/blob/master/src/app/home/home.page.ts#L100.

To answer your actual question, the relationship between `com.zebra.ionicdemo.ACTION` is the value registered at https://github.com/ZebraDevs/DataWedge-Ionic-Demo/blob/master/src/app/providers/barcode/barcode.ts#L25 must match the value being sent, defined at https://github.com/ZebraDevs/DataWedge-Ionic-Demo/blob/master/src/app/home/home.page.ts#L116

**Comment by forexknight** [comment]
@darryncampbell Thank you!
